# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shashwat Priyadarshi
title: Graduate student at Arizona State University
email: spriyad4@asu.edu
GitHub: www.github.com/shashwat2511

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  shashwat2511
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: shashwatpriyadarshi
instagram_username: theonlyshashwat
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
  # icon: fas fa-globe
  # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Shashwat and I'm a Graduate student at Arizona State University with 5 years of experience in Software Development. I am currenltly seeking for Summer’22 Internship where I could utilize my education and skill at fullest.
  I also have experience in Software Development, Design, Integration, Debugging, Automation, and Data Analytics. I have expertise in designing microservice and monolithic based architecture and developing REST APIs using web frameworks like Flask and Falcon.
  
  I have worked at a number of companies gaining teamwork and leadership skills.
  I am most skilled in: <mark>Python</mark> and <mark>Eating Biryani</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mresult
        link: www.mresult.com
        # link_text: Mresult.com
        sub_title: Senior Software Engineer
        caption: January 2020 - June 2021
        # quote: Project Name - Risk Detection application
        description: | # this will include new lines to allow paragraphs
          <mark>Project Name : Risk Detection application</mark>	
          - Designed a <mark>desktop application</mark> to search information from rich-text documents, images, WhatsApp chats & emails using Apache SOLR.
          - Designed and developed <mark>microservices</mark> using <mark>Python</mark> for text extraction, file sorting and SOLR cores creation & indexing for images, documents, chats, and emails.
          - Created a visualization tool to import data and view different analytics over it using <mark>D3.js & PostgreSQL</mark>.
      
      - layout: left
        title: Accenture
        link: www.accenture.com
        # link_text: Accenture.com
        sub_title: Senior Software Engineer
        caption: May 2016 - December 2019
        # quote: 
        description: | # this will include new lines to allow paragraphs
            <mark>Project Name : Machine Reading Comprehension ChatBot</mark>	
            - Developed <mark>microservices</mark> using <mark>Falcon</mark> to interact with Machine Comprehension and Q&A Generator models.
            - Implemented <mark>cache-based system</mark> & <mark>multiprocessing</mark> to <mark>reduce 30% execution time</mark> of APIs.
            - Created packages to manage lengthy requests with <mark>Apache Airflow</mark> utilizing the <mark>DAG paradigm</mark> to migrate the pipelines, earlier running on crontabs. 

            Project Name : Automated Cargo-Booking system & Cargo BOT 
            - Developed <mark>1-click automation</mark> tool for Cargo Booking using IBM WebSphere for Air France & KLM.
            - Created packages to build components (buses, queues, topics etc.) inside multiple application servers.
            - Developed conversational <mark>chatbot with 72% accuracy</mark> using <mark>RASA</mark> to answer queries based on historical data and improved its accuracy by 14% using a user feedback loop.
            - The automation led to an <mark>annual saving of $40K</mark> and reducing work of 4 full-time resources

            Project Name : Server Management application
            - Developed an automation tool to continuously monitor <mark>400+ jobs</mark> running on <mark>16+</mark> servers and generated reports, <mark>saving $30K annually</mark> for the business.
            - Created a <mark>log-visualizer</mark> to utilize information from log files and transform them into <mark>Grafana dashboards</mark>.

            Project Name : Learning & Assessment Webapps (Accenture)
            - Developed <mark>Flask</mark> based <mark>REST APIs</mark> to fulfill multiple purposes like Learning, Training and Assessment. 
            - Developed a completely automated reporting tool with SMTP to send out emails with attached reports.


  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Arizona State University
        caption: 2021 - 2023
        sub_title: MS in Computer Software Engineering
        description: | # this will include new lines to allow paragraphs
          Courses: Advance Data Structure and Algorithms, Foundation of Software Engineering, Data Processing at Scale.
      
      - layout: left
        title: KIIT University
        caption: 2012 - 2016
        sub_title: B.Tech in Computer Science
        description: | # this will include new lines to allow paragraphs
          Courses: Data Structure and Algorithms, Design and Analysis of Algorithm, AI, Computer Networks, Database and Management System, Software Engineering.
  

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in distributed systems and software engineering some of my other interests and hobbies are:
      - Hiking
      - Trekking
      - Gaming
      - Cricket
    # - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

    #  Look at this cool image  
    #  ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
