# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shashwat Priyadarshi
title: Graduate student at Arizona State University
email: spriyad4@asu.edu
GitHub: www.github.com/shashwat2511

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  shashwat2511
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: shashwatpriyadarshi
instagram_username: theonlyshashwat
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
  # icon: fas fa-globe
  # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Shashwat and I'm a Graduate student at Arizona State University with 5 years of experience in Software Development. I am currenltly seeking for Summer’22 Internship where I could utilize my education and skill at fullest.
  I also have experience in Software Development, Design, Integration, Debugging, Automation, and Data Analytics. I have expertise in designing microservice and monolithic based architecture and developing REST APIs using web frameworks like Flask and Falcon.
  
  I have worked at a number of companies gaining teamwork and leadership skills.
  I am most skilled in: <mark>Python</mark> and <b>Eating Biryani</b>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mresult
        link: www.mresult.com
        # link_text: Mresult.com
        sub_title: Senior Software Engineer
        caption: January 2020 - June 2021
        # quote: Project Name - Risk Detection application
        description: | # this will include new lines to allow paragraphs
          Project Name : Risk Detection application
          - Designed a <b>desktop application</b> to search information from rich-text documents, images, WhatsApp chats & emails using Apache SOLR.
          - Designed and developed <b>microservices</b> using <b>Python</b> for text extraction, file sorting and SOLR cores creation & indexing for images, documents, chats, and emails.
          - Created a visualization tool to import data and view different analytics over it using <b>D3.js & PostgreSQL</b>.
      
      - layout: left
        title: Accenture
        link: www.accenture.com
        # link_text: Accenture.com
        sub_title: Senior Software Engineer
        caption: May 2016 - December 2019
        # quote: 
        description: | # this will include new lines to allow paragraphs
            Project Name : Machine Reading Comprehension ChatBot	
            - Developed <b>microservices</b> using <b>Falcon</b> to interact with Machine Comprehension and Q&A Generator models.
            - Implemented <b>cache-based system</b> & <b>multiprocessing</b> to <b>reduce 30% execution time</b> of APIs.
            - Created packages to manage lengthy requests with <b>Apache Airflow</b> utilizing the <b>DAG paradigm</b> to migrate the pipelines, earlier running on crontabs. 

            Project Name : Automated Cargo-Booking system & Cargo BOT
            - Developed <b>1-click automation</b> tool for Cargo Booking using IBM WebSphere for Air France & KLM.
            - Created packages to build components (buses, queues, topics etc.) inside multiple application servers.
            - Developed conversational <b>chatbot with 72% accuracy</b> using <b>RASA</b> to answer queries based on historical data and improved its accuracy by 14% using a user feedback loop.
            - The automation led to an <b>annual saving of $40K</b> and reducing work of 4 full-time resources

            Project Name : Server Management application
            - Developed an automation tool to continuously monitor <b>400+ jobs</b> running on <b>16+</b> servers and generated reports, <b>saving $30K annually</b> for the business.
            - Created a <b>log-visualizer</b> to utilize information from log files and transform them into <b>Grafana dashboards</b>.

            Project Name : Learning & Assessment Webapps (Accenture)
            - Developed <b>PHP</b> based <b>REST APIs</b> to fulfil multiple purposes like Learning, Training and Assessment.
            - Developed a completely automated reporting tool with SMTP to send out emails with attached reports.
            - Performed different analytics on the user data collected by the application and provided automated email reports with visualizations using Python, JS, HTML, and CSS.
            - Implemented Optical Character Recognition to extract data from scanned mark sheets of the job applicants.
            - Designed the UX in Photoshop and developed the UI using HTML, SASS, Bootstrap, jQuery, Gulp.


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Web Developer (Freelance)
        link: http://electrie.in/
        # link_text: Project Website
        sub_title: Software Engineer Intern
        caption: December 2014 - March 2015
        additional_links:
          - title:  http://misragroup.in/
            icon: fab fa-github
            url: http://misragroup.in/
        description: | # this will include new lines to allow paragraphs
          - Developed multiple websites for clients using Wordpress, b, HTML, CSS, JavaScript.
          - Developed custom plugins for Wordpress for few clients.
          - Links of my work: <a href="http://misragroup.in/">http://misragroup.in/</a> , <a href="http://electrie.in/">http://electrie.in/</a>

      - layout: left
        title: First-e-Mart, IIT, Kharagpur, India
        link: http://www.firstemart.com/
        # link_text: Project Website
        sub_title: Software Engineer Intern
        caption: May 2015 - July 2015
        description: | # this will include new lines to allow paragraphs
          - Developed an affiliation website to compare products of different ecommerce websites such as Flipkart, Snapdeal, Amazon and others using PHP.
          - Implemented multiple filters and sorting to view products based on their specifications.
          - Implemented Restful architecture using PHP and MySQL and developed the Bootstrap based UI.
          - Created Python scripts to automatically update the prices of products on the website using API calls.

      - layout: left
        title: Feedback Monitoring System, KIIT University, Bhubaneswar, India
        link: http://www.firstemart.com/
        # link_text: Project Website
        sub_title: Research Assistant
        caption: August 2014 - January 2015
        description: | # this will include new lines to allow paragraphs
          - Developed a <b>PHP</b> based web application to evaluate course feedbacks of the faculties provided by students.
          - Created dynamic forms to record and evaluate feedbacks from <b>22,000 students</b> for around <b>500 teaching staffs</b> of KIIT University.
          - Created <b>performance metrics</b> for faculties based on the student feedbacks.

      - layout: left
        title: Hospital Management System
        # link_text: Project Website
        sub_title: Minor Project
        caption: October 2015 - February 2016
        description: | # this will include new lines to allow paragraphs
          - Developed search engine using <b>Apache SOLR</b> for fast and efficient searching of patient history based on multiple parameter disease and symptoms.
          - Developed the REST APIs using <b>CodeIgniter PHP</b> and <b>MySQL</b> to manage the records.
          - Created modules to generate bill for pharmacy in printer friendly format.

      - layout: left
        title: Audio Transcript Generator Software
        # link_text: Project Website
        sub_title: Minor Project
        caption: March 2014 - June 2014
        description: | # this will include new lines to allow paragraphs
          - Developed an <b>audio transcript generator</b> software integrated with an audio player in Python using the FFmpeg library (a large suite of libraries and programs for handling multimedia files).
          - Developed a <b>python</b> client that interacts with the <b>IBM Watson Speech-To-Text service</b> through its WebSockets interface and receives recognition hypotheses in real time.
          - Audio player could simultaneously play the audio as well as highlights the speech being made in the audio.
          - Implemented all the basic features in the player like play, pause, fast-forward, rewind, playlist etc.



  
  - title: Education
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Arizona State University
        caption: 2021 - 2023
        sub_title: MS in Computer Software Engineering
        description: | # this will include new lines to allow paragraphs
          Courses: Advance Data Structure and Algorithms, Foundation of Software Engineering, Data Processing at Scale.
      
      - layout: left
        title: KIIT University
        caption: 2012 - 2016
        sub_title: B.Tech in Computer Science
        description: | # this will include new lines to allow paragraphs
          Courses: Data Structure and Algorithms, Design and Analysis of Algorithm, AI, Computer Networks, Database and Management System, Software Engineering.
  

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in distributed systems and software engineering some of my other interests and hobbies are:
      - Hiking
      - Trekking
      - Gaming
      - Cricket
    # - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

    #  Look at this cool image  
    #  ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
